### PR TITLE
Handle variable expansion and '#' inside shell, support inherit_defer directive

### PR DESCRIPTION
**Pull request by idillon-sfl**
1. This adds variable expansions to shell functions.

BitBake code:
```
foo(){
    echo ${BAR}
}
```
parsing:
```
(recipe [0, 0] - [2, 1]
  (function_definition [0, 0] - [2, 1]
    (identifier [0, 0] - [0, 3])`
    (shell_content [1, 4] - [1, 9])
    (variable_expansion [1, 9] - [1, 15]
      (identifier [1, 11] - [1, 14]))))
```

Real life example: https://git.yoctoproject.org/poky/tree/meta/recipes-core/busybox/busybox.inc?h=mickledore#n117

2. This also fixes a bug where `#` was considered as a comment in a shell string. It simply ensures any `#` will be considered `shell_content`.
Bitbake code:
```
foo () {
  '${}#'
}
```

parsing before:
```
(recipe [0, 0] - [2, 1]
  (ERROR [0, 0] - [2, 1]
    (function_definition [0, 0] - [1, 6]
      (identifier [0, 0] - [0, 3])
      (ERROR [0, 8] - [1, 5]
        (string_start [1, 2] - [1, 3])))
    (comment [1, 6] - [1, 8])))
```

parsing after:
```
(recipe [0, 0] - [2, 1]
  (function_definition [0, 0] - [2, 1]
    (identifier [0, 0] - [0, 3])
    (shell_content [1, 2] - [1, 7])
    (variable_expansion [1, 7] - [1, 10])
    (shell_content [1, 10] - [1, 12])
```
Real life example: https://git.yoctoproject.org/poky/tree/meta/recipes-core/base-files/base-files_3.0.14.bb#n126

3. This also includes [my colleague's PR](https://github.com/tree-sitter-grammars/tree-sitter-bitbake/pull/21) in order to make the whole thing easier to merge

### CODE REVIEW

**Comment by amaanq** [comment]
Hey, thanks for your PRs! I'll take a look at them and see if I can improve them, but also, I prefer one PR that might fix a few issues - for a few reasons

- It allows us to generate the parser/grammar files in one go, instead of via multiple PRs that need to be rebased
- It can be easier to review if the changes aren't too big

So I'll probably cherry pick this commit onto your other PR, since it's a bit bigger

**Comment by idillon-sfl** [comment]
Hello!

If you don't mind, we'd really appreciate to have this merged. We'd like to avoid maintaining our own separate fork, and this functionality would help us with real life use cases.

Thank you a lot

**Comment by idillon-sfl** [comment]
I added a new fix. I described what it does in the first comment: https://github.com/tree-sitter-grammars/tree-sitter-bitbake/pull/19#issue-2111501607

**Comment by idillon-sfl** [comment]
Abandoned for #23.

We gave up trying to support shell variable expansions. This was too much trouble. We use tree-sitter-bash instead for shell regions.

**Pull request closed without merging**
