### PR TITLE
feat: parse variable expansion in include path

### PR DESCRIPTION
**Pull request by WilsonZiweiWang**
This change should allow the parser to recognize the variable expansion syntax in the `include_path`.
Example from `poky`:
https://github.com/yoctoproject/poky/blob/348d9aba3305cd98b0c0b1ec0f4b1407e786307a/meta/recipes-core/glibc/glibc-y2038-tests_2.38.bb#L1

Sample result:
image

### CODE REVIEW

**Comment by amaanq** [comment]
thanks for the PR. it looks like a few of them fail in your screenshot output, is that intentional because of the unclosed quote? that's fine with me if so

**Comment by WilsonZiweiWang** [comment]
> thanks for the PR. it looks like a few of them fail in your screenshot output, is that intentional because of the unclosed quote? that's fine with me if so

yes, I put the `"` after the `$` so none of the choices should match.

**Comment by amaanq** [comment]
just gonna force push your generated changes using tree-sitter cli on master, otherwise LGTM

**Comment by amaanq** [comment]
thanks!

**Pull request merged**
