### PR TITLE
Fix braces in shell strings

### LINKED ISSUE #13: Inside a bash function, a bracket inside a string or a comment will give an error
A bracket inside a string inside a function gives an error
```
d() {
  t = '{'
}
```

A bracket inside a comment gives an error
```
do() {
  # {
}
```

It does work inside python functions, though

Thank you

### PR DESCRIPTION
**Pull request by idillon-sfl**
This is my attempt to fix #13 

```
foo(){
    echo '}'
}
```

```
(recipe [0, 0] - [2, 1]
  (function_definition [0, 0] - [2, 1]
    (identifier [0, 0] - [0, 3])
    (shell_content [1, 4] - [1, 10])
    (shell_content [1, 10] - [1, 12])))
```

This is not perfect. We'd rather have a single shell_content. But for now this is the best I could do, and it is better than having errors.

### CODE REVIEW

**Comment by amaanq** [comment]
I've fixed this to have it retain one node - basically we'll disregard the balancing of braces if we're inside quotes.

**Comment by amaanq** [comment]
Just an FYI - you might benefit from injecting bash inside shell content nodes to get better parse output - on nodes where you detect a ${ anywhere, or any shell content. I would really look into this as injections might save you a huge amount of time with just letting the bash parser parse those bits.

I'll leave out on adding that PR's commit on top of this

Thanks for this fix!

**Comment by idillon-sfl** [comment]
Nice improvements on my PR!

What do you call "injecting bash inside shell content node"?

I noticed the [python.js](https://github.com/amaanq/tree-sitter-bitbake/blob/master/python.js) looks like a modified version of [grammar.js](https://github.com/tree-sitter/tree-sitter-python/commits/master/grammar.js) on tree-sitter-python. Are you suggesting to add a bash.js file from the [grammar.js](https://github.com/tree-sitter/tree-sitter-bash/blob/master/grammar.js) file of tree-sitter-bash?

**Comment by amaanq** [comment]
What I mean is using an injections.scm query, I was actually going to do that for here with python, by just injecting python into `python content` nodes, but it became impossible to just arbitrarily parse python code and know when to stop, so I embedded a mini-python grammar here, which is not something you'll probably see anywhere else (similar concept done with my Cairo grammar though for Cairo 0.x and 1.0 being so different)


You should check out the docs here:
https://tree-sitter.github.io/tree-sitter/syntax-highlighting#language-injection

You can set specific ranges to *re-parse* using another language, e.g. shell_content nodes using bash. You will then get a mini bash CST inside the bitbake tree, which allows you to leverage a full-blown bash parser instead of adding hacky workaround here!

Feel free to join the discord and ask more questions you might have, tree-sitter is a huge project with many various components tightly coupled together to make it work, so learning it can be quite hard

**Pull request merged**
